"""
dashboard_streamlit.py
----------------------
Streamlit dashboard for P4: Global Equity Market Dashboard.
Reads data/heatmap_data.csv (generated by fetch_data.py / main.py).

Run:
    streamlit run dashboard_streamlit.py
"""

from __future__ import annotations

import os
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

# ---------------------------------------------------------------------------
# Page config
# ---------------------------------------------------------------------------
st.set_page_config(
    page_title="Global Market Heatmap",
    page_icon="📊",
    layout="wide",
)

st.markdown(
    """
    <style>
    @import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600&family=IBM+Plex+Sans:wght@300;400;600&display=swap');
    html, body, [class*="css"] { font-family: 'IBM Plex Sans', sans-serif; }
    .stMetric label  { font-family: 'IBM Plex Mono', monospace; font-size: 0.72rem;
                       color: #888; text-transform: uppercase; letter-spacing: 0.08em; }
    .stMetric value  { font-family: 'IBM Plex Mono', monospace; font-size: 1.6rem; font-weight: 600; }
    .block-container { padding-top: 1.8rem; padding-bottom: 2rem; }
    h1 { font-family: 'IBM Plex Mono', monospace; font-weight: 600; letter-spacing: -0.02em; }
    h2, h3 { font-family: 'IBM Plex Sans', sans-serif; font-weight: 600; }
    .stSelectbox label, .stMultiSelect label {
        font-family: 'IBM Plex Mono', monospace;
        font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.06em;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
DATA_PATH = Path("data") / "heatmap_data.csv"
HEATMAP_COLORS = [
    [0.00, "#c0392b"],
    [0.35, "#7f1d1d"],
    [0.50, "#1a1a2e"],
    [0.65, "#1a472a"],
    [1.00, "#27ae60"],
]
BAR_COLOR_SCALE = ["#c0392b", "#f39c12", "#27ae60"]
TRANSPARENT     = "rgba(0,0,0,0)"
GRID_COLOR      = "rgba(128,128,128,0.15)"

# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

@st.cache_data(ttl=300)
def load_data() -> pd.DataFrame:
    if not DATA_PATH.exists():
        return pd.DataFrame()
    df = pd.read_csv(DATA_PATH)
    df["MarketCapB"] = pd.to_numeric(df["MarketCap"], errors="coerce") / 1e9
    df["AbsChange"]  = df["ChangePct"].abs()
    return df


df = load_data()

# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------
st.title("📊 Global Market Heatmap")
st.caption("Risk · Return · Sector · Size — Indian & US equities")

if df.empty:
    st.error(
        "No data found. Run `python main.py` first to generate `data/heatmap_data.csv`."
    )
    st.stop()

# ---------------------------------------------------------------------------
# Sidebar filters
# ---------------------------------------------------------------------------
st.sidebar.header("Filters")

all_countries = sorted(df["Country"].dropna().unique().tolist())
all_sectors   = sorted(df["Sector"].dropna().unique().tolist())

sel_country = st.sidebar.selectbox("Country", ["All"] + all_countries)
sel_sectors = st.sidebar.multiselect("Sector", all_sectors, default=all_sectors)
min_mcap    = st.sidebar.slider(
    "Min Market Cap (B USD)",
    min_value=0.0,
    max_value=float(df["MarketCapB"].max() or 1_000.0),
    value=0.0,
    step=10.0,
)

fdf = df.copy()
if sel_country != "All":
    fdf = fdf[fdf["Country"] == sel_country]
if sel_sectors:
    fdf = fdf[fdf["Sector"].isin(sel_sectors)]
fdf = fdf[fdf["MarketCapB"] >= min_mcap]

st.sidebar.markdown(f"**{len(fdf)} stocks** selected")

if st.sidebar.button("🔄 Refresh Data"):
    st.cache_data.clear()
    st.rerun()

# ---------------------------------------------------------------------------
# KPI row
# ---------------------------------------------------------------------------
st.divider()
k1, k2, k3, k4, k5 = st.columns(5)

valid_cagr   = fdf["CAGR"].dropna()
valid_sharpe = fdf["Sharpe"].dropna()
valid_dd     = fdf["Max_Drawdown"].dropna()

with k1:
    st.metric("Avg CAGR (3yr)", f"{valid_cagr.mean():.1f}%" if len(valid_cagr) else "—")
with k2:
    st.metric("Avg Sharpe", f"{valid_sharpe.mean():.2f}" if len(valid_sharpe) else "—")
with k3:
    st.metric("Avg Max Drawdown", f"{valid_dd.mean():.1f}%" if len(valid_dd) else "—")
with k4:
    if len(valid_cagr):
        best_idx = fdf["CAGR"].idxmax()
        best_label = f"{fdf.loc[best_idx, 'Ticker']}  ({fdf.loc[best_idx, 'CAGR']:.1f}%)"
    else:
        best_label = "—"
    st.metric("Top CAGR Stock", best_label)
with k5:
    gainers = int((fdf["ChangePct"] > 0).sum())
    losers  = int((fdf["ChangePct"] < 0).sum())
    st.metric("Gainers / Losers", f"{gainers} / {losers}")

st.divider()

# ---------------------------------------------------------------------------
# Main charts
# ---------------------------------------------------------------------------
col_left, col_right = st.columns([3, 2], gap="large")

# ── Treemap ──────────────────────────────────────────────────────────────────
with col_left:
    st.subheader("Sector Heatmap")
    st.caption("Tile size = Market Cap  ·  Colour = Daily % Change")

    hm_df = fdf.dropna(subset=["MarketCapB", "ChangePct", "Sector"])
    if hm_df.empty:
        st.info("No data for treemap with current filters.")
    else:
        color_bound = max(abs(hm_df["ChangePct"].min()), abs(hm_df["ChangePct"].max()), 2.0)
        fig_tree = px.treemap(
            hm_df,
            path=[px.Constant("Market"), "Country", "Sector", "Ticker"],
            values="MarketCapB",
            color="ChangePct",
            color_continuous_scale=HEATMAP_COLORS,
            color_continuous_midpoint=0,
            range_color=[-color_bound, color_bound],
            custom_data=["Ticker", "Sector", "ChangePct", "MarketCapB", "CAGR", "Sharpe"],
        )
        fig_tree.update_traces(
            hovertemplate=(
                "<b>%{customdata[0]}</b><br>"
                "Sector: %{customdata[1]}<br>"
                "Change: %{customdata[2]:+.2f}%<br>"
                "Mkt Cap: $%{customdata[3]:.1f}B<br>"
                "CAGR (3yr): %{customdata[4]:.1f}%<br>"
                "Sharpe: %{customdata[5]:.2f}"
                "<extra></extra>"
            ),
            texttemplate="<b>%{label}</b><br>%{customdata[2]:+.1f}%",
        )
        fig_tree.update_layout(
            margin=dict(t=0, l=0, r=0, b=0),
            height=460,
            coloraxis_colorbar=dict(title="Change %", tickformat="+.1f", thickness=12, len=0.6),
            paper_bgcolor=TRANSPARENT,
            plot_bgcolor=TRANSPARENT,
        )
        st.plotly_chart(fig_tree, use_container_width=True)

# ── Risk-Return scatter ───────────────────────────────────────────────────────
with col_right:
    st.subheader("Risk vs Return")
    st.caption("X = Max Drawdown  ·  Y = CAGR  ·  Bubble = Sharpe")

    sc_df = fdf.dropna(subset=["Max_Drawdown", "CAGR", "Sharpe"])
    if sc_df.empty:
        st.info("No KPI data yet — run the pipeline to compute CAGR / Sharpe / MaxDD.")
    else:
        sharpe_range = sc_df["Sharpe"].max() - sc_df["Sharpe"].min() + 1e-9
        sharpe_norm  = (sc_df["Sharpe"] - sc_df["Sharpe"].min()) / sharpe_range
        bubble_size  = 8 + sharpe_norm * 32

        fig_sc = go.Figure()
        fig_sc.add_shape(
            type="rect",
            x0=sc_df["Max_Drawdown"].min() - 2,
            x1=sc_df["Max_Drawdown"].mean(),
            y0=sc_df["CAGR"].mean(),
            y1=sc_df["CAGR"].max() + 5,
            fillcolor="rgba(39,174,96,0.07)",
            line_width=0,
        )
        fig_sc.add_hline(y=sc_df["CAGR"].mean(), line_dash="dot", line_color="gray", line_width=0.8)
        fig_sc.add_vline(x=sc_df["Max_Drawdown"].mean(), line_dash="dot", line_color="gray", line_width=0.8)

        for country, grp in sc_df.groupby("Country"):
            idx = grp.index
            fig_sc.add_trace(
                go.Scatter(
                    x=grp["Max_Drawdown"],
                    y=grp["CAGR"],
                    mode="markers+text",
                    name=str(country),
                    text=grp["Ticker"],
                    textposition="top center",
                    textfont=dict(size=9),
                    marker=dict(
                        size=bubble_size.loc[idx].tolist(),
                        opacity=0.82,
                        line=dict(width=1, color="rgba(255,255,255,0.3)"),
                    ),
                    customdata=grp[["Ticker", "Sector", "CAGR", "Sharpe", "Max_Drawdown"]].values,
                    hovertemplate=(
                        "<b>%{customdata[0]}</b><br>"
                        "%{customdata[1]}<br>"
                        "CAGR: %{customdata[2]:.1f}%<br>"
                        "Sharpe: %{customdata[3]:.2f}<br>"
                        "Max DD: %{customdata[4]:.1f}%"
                        "<extra></extra>"
                    ),
                )
            )

        fig_sc.update_layout(
            xaxis_title="Max Drawdown (%)",
            yaxis_title="CAGR 3yr (%)",
            height=460,
            margin=dict(t=10, l=10, r=10, b=40),
            legend=dict(orientation="h", y=-0.12),
            paper_bgcolor=TRANSPARENT,
            plot_bgcolor=TRANSPARENT,
        )
        fig_sc.update_xaxes(showgrid=True, gridcolor=GRID_COLOR)
        fig_sc.update_yaxes(showgrid=True, gridcolor=GRID_COLOR)
        st.plotly_chart(fig_sc, use_container_width=True)

st.divider()

# ---------------------------------------------------------------------------
# Sector bar charts
# ---------------------------------------------------------------------------
col_b1, col_b2 = st.columns(2, gap="large")


def _horizontal_bar(df_in: pd.DataFrame, x_col: str, title: str, x_label: str) -> None:
    """Render a horizontal bar chart sorted ascending."""
    data = (
        df_in.groupby("Sector")[x_col]
        .mean()
        .dropna()
        .sort_values(ascending=True)
        .reset_index()
    )
    if data.empty:
        st.info(f"No {x_col} data available.")
        return
    fig = px.bar(
        data, x=x_col, y="Sector", orientation="h",
        color=x_col,
        color_continuous_scale=BAR_COLOR_SCALE,
        labels={x_col: x_label},
    )
    fig.update_layout(
        height=320,
        margin=dict(t=10, b=10, l=10, r=10),
        coloraxis_showscale=False,
        paper_bgcolor=TRANSPARENT,
        plot_bgcolor=TRANSPARENT,
    )
    fig.update_xaxes(showgrid=True, gridcolor=GRID_COLOR)
    st.plotly_chart(fig, use_container_width=True)


with col_b1:
    st.subheader("Avg CAGR by Sector")
    _horizontal_bar(fdf, "CAGR", "Avg CAGR by Sector", "Avg CAGR (%)")

with col_b2:
    st.subheader("Avg Sharpe by Sector")
    _horizontal_bar(fdf, "Sharpe", "Avg Sharpe by Sector", "Avg Sharpe Ratio")

st.divider()

# ---------------------------------------------------------------------------
# Data table
# ---------------------------------------------------------------------------
st.subheader("Stock Data Table")

DISPLAY_COLS = [
    "Ticker", "Name", "Sector", "Country",
    "CurrentPrice", "ChangePct", "MarketCapB",
    "CAGR", "Sharpe", "Max_Drawdown", "Avg_Vol_30d",
]
show_cols = [c for c in DISPLAY_COLS if c in fdf.columns]
table_df  = (
    fdf[show_cols]
    .copy()
    .rename(columns={"MarketCapB": "MktCap (B)"})
    .sort_values("CAGR", ascending=False)
    .reset_index(drop=True)
)

fmt = {
    "CurrentPrice": "{:.2f}",
    "ChangePct":    "{:+.2f}%",
    "MktCap (B)":  "{:.1f}",
    "CAGR":        "{:.1f}%",
    "Sharpe":      "{:.2f}",
    "Max_Drawdown":"{:.1f}%",
}
active_fmt = {k: v for k, v in fmt.items() if k in table_df.columns}

styled = (
    table_df.style
    .format(active_fmt, na_rep="—")
    .background_gradient(subset=[c for c in ["CAGR"] if c in table_df.columns],
                         cmap="RdYlGn", vmin=-10, vmax=40)
    .background_gradient(subset=[c for c in ["Sharpe"] if c in table_df.columns],
                         cmap="RdYlGn", vmin=-0.5, vmax=2)
    .background_gradient(subset=[c for c in ["ChangePct"] if c in table_df.columns],
                         cmap="RdYlGn", vmin=-5, vmax=5)
)

st.dataframe(styled, use_container_width=True, height=420)